[build]
  command = "npm install && npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "20.18.0" }
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]
  external_node_modules = ["pg", "pg-native"]

[dev]
  functions = "netlify/functions"
  publish = "dist"
  port = 8888
  framework = "vite"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
